apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-listing.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store-listing.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "store-listing.redis.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "store-listing.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
        app.kubernetes.io/name: {{ include "store-listing.redis.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
