{{- if .Values.secrets.jwtPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-listing.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store-listing.labels" . | nindent 4 }}
stringData:
  publicKey.pem: {{ .Values.secrets.jwtPublicKey | quote }}
{{- end }}