apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "store-listing.trend-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store-listing.labels" . | nindent 4 }}
    app.kubernetes.io/component: trend-service
spec:
  to:
    kind: Service
    name: {{ include "store-listing.trend-service.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
