apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-listing.app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store-listing.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    {{- include "store-listing.app.selectorLabels" . | nindent 4 }}
